version: 2

jobs:
  build-and-publish:
    docker:
      - image: cimg/python:3.10

    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Publish Docker image
          command: |
            # Build image
            docker build \
              -t ${DOCKER_REPO}/spidyquotes/${CIRCLE_BRANCH,,}:${CIRCLE_SHA1:0:7} \
              .

            # Docker login
            docker login \
              -u ${DOCKER_USER} \
              -p ${DOCKER_PASS} \
              ${DOCKER_REPO}

            # Push image
            docker push \
              ${DOCKER_REPO}/spidyquotes/${CIRCLE_BRANCH,,}:${CIRCLE_SHA1:0:7}

workflows:
  version: 2
  build-and-publish-workflow:
    jobs:
      - build-and-publish
